-- MySQL Script generated by MySQL Workbench
-- Sat 15 Apr 2017 02:27:18 AM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DBMS_Project
-- -----------------------------------------------------
-- For DBMS Project 

-- -----------------------------------------------------
-- Schema DBMS_Project
--
-- For DBMS Project 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBMS_Project` DEFAULT CHARACTER SET utf8 ;
USE `DBMS_Project` ;

-- -----------------------------------------------------
-- Table `DBMS_Project`.`Manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMS_Project`.`Manufacturer` (
  `idManufacturer` VARCHAR(45) NOT NULL,
  `Transport` VARCHAR(45) NOT NULL,
  `Tracking` VARCHAR(45) NOT NULL,
  `Loading` VARCHAR(45) NOT NULL,
  `Delivery_Days` INT NOT NULL,
  `Packaging` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idManufacturer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMS_Project`.`Transporter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMS_Project`.`Transporter` (
  `idTransporter` VARCHAR(45) NOT NULL,
  `Theft` INT NOT NULL,
  `Delay` INT NOT NULL,
  `Damages` INT NOT NULL,
  PRIMARY KEY (`idTransporter`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMS_Project`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMS_Project`.`Cargo` (
  `Category` VARCHAR(45) NOT NULL,
  `Weight` INT NOT NULL,
  `Volume` INT NOT NULL,
  `Manufacturer` VARCHAR(45) NOT NULL,
  INDEX `idManufacturer _idx` (`Manufacturer` ASC),
  CONSTRAINT `fk_manufacturer_cargo`
    FOREIGN KEY (`Manufacturer`)
    REFERENCES `DBMS_Project`.`Manufacturer` (`idManufacturer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMS_Project`.`Truck`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMS_Project`.`Truck` (
  `Manufacturer` VARCHAR(45) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Dimension` INT NOT NULL,
  `Freigth_Cost` INT NOT NULL,
  INDEX `idManufacturer _idx` (`Manufacturer` ASC),
  CONSTRAINT `fk_manufacturer_truck`
    FOREIGN KEY (`Manufacturer`)
    REFERENCES `DBMS_Project`.`Manufacturer` (`idManufacturer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMS_Project`.`Facility Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMS_Project`.`Facility Type` (
  `Type` VARCHAR(45) NOT NULL,
  ` Location` INT NOT NULL,
  `Distance` INT NOT NULL,
  `Manufacture` VARCHAR(45) NOT NULL,
  INDEX `idManufacturer _idx` (`Manufacture` ASC),
  CONSTRAINT `fk_manufacturer_facility`
    FOREIGN KEY (`Manufacture`)
    REFERENCES `DBMS_Project`.`Manufacturer` (`idManufacturer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMS_Project`.`Shipment Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMS_Project`.`Shipment Details` (
  `Transporter` VARCHAR(45) NOT NULL,
  `Cargo_Weight` INT NOT NULL,
  `Freight` INT NOT NULL,
  `Loading_Type` VARCHAR(45) NOT NULL,
  `Cargo_Details` VARCHAR(45) NOT NULL,
  `Dispatch_Month` INT NOT NULL,
  INDEX `idTransporter_idx` (`Transporter` ASC),
  CONSTRAINT `fk_transporter_shipment`
    FOREIGN KEY (`Transporter`)
    REFERENCES `DBMS_Project`.`Transporter` (`idTransporter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBMS_Project`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBMS_Project`.`Rating` (
  `Rating` INT NOT NULL,
  `Transporter` VARCHAR(45) NOT NULL,
  `Manufacturer` VARCHAR(45) NOT NULL,
  INDEX `idTransporter _idx` (`Transporter` ASC),
  CONSTRAINT `fk_transporter_rating`
    FOREIGN KEY (`Transporter`)
    REFERENCES `DBMS_Project`.`Transporter` (`idTransporter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
